### ISSUE TITLE
Advanced patterns: Better info about Generic Systems

### ISSUE THREAD

**Issue by jamadazi** [bevy-cheatbook/bevy-cheatbook#10]
Talk about other uses of Generic Systems.

In combination with Traits?

In combination with Const Generics?

---

Please share information you know about use cases we should cover, if you are knowledgeable about this.

**Comment by alice-i-cecile** [comment]
@aevyrie's plugins (bevy_mod_picking etc) are super useful as mature examples of this pattern. 

Traits can be very useful, in order to ensure that you're only operating on data of the appropriate types.

Const generics are a very good way to reduce type proliferation when you really need to process data in separate systems. Think `Side=1` or `Grid = Hex`. They become much more useful in Bevy with enum const generics though, so you should have advice on how to enable the const-generics feature on nightly.

Another thing to add: automatic labelling of generic systems is tricky to figure out but there's a nice snippet for it.

**Comment by aevyrie** [comment]
> @aevyrie's plugins (bevy_mod_picking etc) are super useful as mature examples of this pattern.

I appreciate the praise, but I feel like most of my work with generic systems is pretty simple. That said, it's a super nice pattern that simplified my code. I'd love to see examples using traits and const generics!

>Another thing to add: automatic labelling of generic systems is tricky to figure out but there's a nice snippet for it.

See discussion here: https://github.com/bevyengine/bevy/issues/1497#issuecomment-785332154
I still think we need a better solution for this other than:

```rust
.label(Cow::Owned(format!("generic_system_name_{}", std::any::type_name::<T>()))),
```

which feels antithetical to most of Bevy's user-facing ergonomics, but that's neither here nor there.

**Comment by alice-i-cecile** [comment]
> I appreciate the praise, but I feel like most of my work with generic systems is pretty simple.

They're a really nice example of non-contrived applications of the pattern, which are hard to come up with when designing in a vacuum <3
