### ISSUE TITLE
 Proposal to Enhance Bevy Learning Resources and Collaboration: Please update to Bevy .12 and merge it to the parent project.

### ISSUE THREAD

**Issue by duaneking** [bevy-cheatbook/bevy-cheatbook#247]
I hope this message finds you well. I've been following your work on the Bevy book and appreciate the effort you've put into creating such a resource. As a fellow enthusiast of the Bevy project, I wanted to discuss a potential idea that could benefit both the Bevy community and your professional goals.

I've noticed that the book has fallen behind the latest updates of Bevy, with multiple versions and API changes not reflected in the current content. This discrepancy has started to impact learners negatively, as they often encounter outdated or incompatible examples. This not only hampers their learning experience but might inadvertently affect the perceived value of your work and freelancing endeavors.

To address this, I'd like to propose an initiative where you update the book to align with at least Bevy 0.12. This would not only refresh the book's relevance but also offer an opportunity to integrate these updates directly into the Bevy project's official documentation. Your expertise and unique examples could significantly enrich the official resources, bridging any gaps in the current documentation.

This could serve multiple purposes:

1. Enhancing the Bevy community's learning experience.
2. Elevating your profile within the community as a contributor to the official Bevy resources.
3. Ensuring that your work remains a valuable and current resource for both new and experienced Bevy users.
4. Alternatively, if updating the book is not feasible, I suggest considering the removal of the outdated content to prevent confusion and misinformation within the Bevy community. This step would help maintain the integrity and accuracy of resources available to Bevy learners, and could be achieved by simply deleting this project from github.

Your contributions to the Bevy project in either capacity would be highly valued and recognized. This effort could also showcase your expertise and dedication, potentially leading to more engagement and opportunities within the Bevy ecosystem, for all we know.

I look forward to hearing your thoughts on this proposal and I hope your willing to work for the betterment of the Bevy community.

**Comment by inodentry** [comment]
Thank you for the compliments.

You think I haven't extensively thought about all of this before?

I am aware of all of this. It is just not an easy task.

If I could "just update everything to the latest release", I would have done it ages ago. You think I don't want to update the book?

It takes a lot of work for a book of this size, literally over a week of full-time work. I don't have the time or mental energy to do that all at once, so I am doing it gradually. A decent portion of the book *is* up to date with 0.12. Many pages are not, and the ones still stuck on 0.9 are, unfortunately, the hardest and most time-consuming to update.

I spent the two weeks leading up to the Bevy 0.12 release working on Cheatbook for a few hours *every day*. As you can see, I only managed to update about half the content.

That is exactly why I the book has the per-page versioning policy. Before (up until Bevy 0.9), I used to think I could keep the whole book up to date, but I burned out. So now, the Bevy version for each page is clearly stated at the top of the page, as to avoid misleading readers, while letting me work through everything at my own pace, as I can manage it.

As for making things official, again, it is not an easy thing.

"Official" is not just a matter of putting the content upstream.

It means working with the project and its organizational structure. I would *not* have been able to write this book at all, if every time I had to make any change, I'd have to go through Bevy's PR review process. The overhead would have actually made it impossible to write a book like Bevy Cheatbook.

Believe me, I *know* that, in an ideal world, having it official would be a good thing. It would give me amazing personal reputation in the community and it would make the book discoverable and allow the community to participate.

But it requires the Bevy Project to have an organizational structure and policies that allow me to do my work and don't get in the way to the point of making it impossible.

The reason why Cheatbook is unofficial is because I needed the freedom and flexibility to work autonomously, if I were to be able to do it *at all*.

Bevy has actually had *several* attempts to make a more comprehensive official book, including some amazing work by Alice, one of Bevy's maintainers. But, as you can see, those efforts went nowhere. Alice's book is stuck in draft form, in some PRs/branches/RFCs. It is not on the website, and you are not reading it, you are reading Cheatbook instead. This is proof that I am right to keep Cheatbook unofficial. At least until the Bevy organization can figure out a strategy to make it viable to write and maintain an official book.

I have had discussions with Bevy maintainers about this topic. We are trying to come up with a plan to improve Bevy's documentation and organizational practices.

Believe me, our goals are aligned. I also want the best for the community.
