### ISSUE TITLE
Events page should mention add_event::<LevelUpEvent>()

### ISSUE THREAD

**Issue by ramirezmike** [bevy-cheatbook/bevy-cheatbook#40]
I got slightly tripped up on events until I realized I was missing 

```App::build().add_event::<LevelUpEvent>()```

The [events page](https://bevy-cheatbook.github.io/next/programming/events.html) doesn't mention this, although it is mentioned on the [App Builder](https://bevy-cheatbook.github.io/next/programming/app-builder.html) page (the next page in the cheatbook). For comparison, the [resources page](https://bevy-cheatbook.github.io/next/programming/res.html) mentions needing to add the resource to the app builder. Additionally, the [systems](https://bevy-cheatbook.github.io/next/programming/systems.html) page does not.

**Comment by jamadazi** [comment]
Good point. I will fix this, I consider it a bug, because:

> ... although it is mentioned on ... the next page in the cheatbook

As specified in the introduction, you shouldn't be expected to read the book in order, or completely, but rather jump to whatever you find useful. Hence, each page needs to either contain or link to all the important relevant information.

I will add information about the app builder to both "systems" and "events".

Thanks for pointing this out!
